# Generated by Django 2.1.7 on 2019-07-25 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0002_readdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpDeatil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('blog', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
