# Generated by Django 2.1.7 on 2019-07-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0003_ipdeatil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdeatil',
            old_name='blog',
            new_name='id_blog',
        ),
    ]
