# Generated by Django 2.1.7 on 2019-07-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0004_auto_20190725_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdeatil',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
